practicalswift,2018-04-17T10:43:04Z,Concept ACK - nice!,https://github.com/bitcoin/bitcoin/pull/13003#issuecomment-381943696,381943696,
MarcoFalke,2018-04-24T17:41:02Z,Added a commit to address the documentation nit,https://github.com/bitcoin/bitcoin/pull/13003#issuecomment-384018950,384018950,
laanwj,2018-04-26T17:45:35Z,utACK fa02c5b38b4343e70ddb656c971c9707075f5a8f ,https://github.com/bitcoin/bitcoin/pull/13003#issuecomment-384728539,384728539,
ryanofsky,2018-04-17T21:55:34Z,"""success is False"" line unintentionally deleted?",https://github.com/bitcoin/bitcoin/pull/13003#discussion_r182253857,182253857,test/functional/test_framework/mininode.py
ryanofsky,2018-04-17T22:01:56Z,"Note to reviewers: The updates in feature_block.py just tweak the network_thread_start/network_thread_join calls to happen in a more logical order, and be consistent with other tests. This is internal test cleanup which is not directly related to the other changes in this PR.",https://github.com/bitcoin/bitcoin/pull/13003#discussion_r182256045,182256045,test/functional/feature_block.py
ryanofsky,2018-04-17T22:07:39Z,"It would be logical to start the network thread adding connections, right? Just asking because it's weird to me to see shutdown order not be the reverse of initialization order like:\n\n```python\nnetwork_thread_start()\nadd_p2p_connection()\n...\ndisconnect_p2ps()\nnetwork_thread_join()\n```",https://github.com/bitcoin/bitcoin/pull/13003#discussion_r182257223,182257223,test/functional/p2p_invalid_tx.py
jamesob,2018-04-17T22:24:34Z,"It looks like including both ""if success is ..."" lines would be repetitive.",https://github.com/bitcoin/bitcoin/pull/13003#discussion_r182260572,182260572,test/functional/test_framework/mininode.py
ryanofsky,2018-04-17T22:43:43Z,"It is a little repetitive, but I think the description is vague without that line because ""not asserting"" and ""asserting not"" mean different things.",https://github.com/bitcoin/bitcoin/pull/13003#discussion_r182264096,182264096,test/functional/test_framework/mininode.py
MarcoFalke,2018-04-17T23:38:56Z,"In `test/functional/README.md` it says ""Call `network_thread_start()` after all `P2PInterface` objects are created ...""",https://github.com/bitcoin/bitcoin/pull/13003#discussion_r182272757,182272757,test/functional/p2p_invalid_tx.py
