achow101,2021-09-30 20:58:19,ACK 0ab4c3b27265401c59e40adc494041927dc9dbe3,https://github.com/bitcoin/bitcoin/pull/23142#issuecomment-931677654,931677654,
laanwj,2021-10-01 08:31:57,"Very much agree with this change, assert is not an error-handling mechanism.\n\nCode review ACK 0ab4c3b27265401c59e40adc494041927dc9dbe3",https://github.com/bitcoin/bitcoin/pull/23142#issuecomment-932032285,932032285,
laanwj,2021-10-01 08:33:25,"Would be good to have a test for this, by the way.\n\nOh I see jonatack brought this up too:\n\n> A test might be good.\n\nDo we need a ""needs test"" label :smile: ",https://github.com/bitcoin/bitcoin/pull/23142#issuecomment-932033185,932033185,
practicalswift,2021-09-30 08:07:37,"```suggestion\n    bool tx_corrupt{false};\n```\n\nTo avoid potential use of uninitialized memory when the logic reading/writing `tx_corrupt` is changed over time.",https://github.com/bitcoin/bitcoin/pull/23142#discussion_r719161537,719161537,src/wallet/walletdb.cpp
jonatack,2021-09-30 10:18:28,"```suggestion\n                if (!new_tx) {\n```",https://github.com/bitcoin/bitcoin/pull/23142#discussion_r719265890,719265890,src/wallet/walletdb.cpp
rajarshimaitra,2021-09-30 12:52:13,"Probably I am missing context here, so feel free to ignore my question.\n\nWhy would we consider ""the tx we just tried to load was already in the wallet."" as a corrupted transaction? If I am missing context here, would it be helpful to clarify this in the above comment?  ",https://github.com/bitcoin/bitcoin/pull/23142#discussion_r719373457,719373457,src/wallet/walletdb.cpp
ryanofsky,2021-09-30 18:37:18,"> Why would we consider ""the tx we just tried to load was already in the wallet."" as a corrupted transaction? If I am missing context here, would it be helpful to clarify this in the above comment?\n\nIt might not be bad to update the comment above or the error message below or the `tx_corrupt` variable name if you have suggestions, but this all seems ok to me. If there are multiple transactions",https://github.com/bitcoin/bitcoin/pull/23142#discussion_r719664644,719664644,src/wallet/walletdb.cpp
rajarshimaitra,2021-09-30 19:05:55,"Hmm. The context I was missing then would be: `!new` suggests that the wallet already loaded the transaction with the given hash.\n\nSo maybe the comment above could read something like ""There's some corruption here since the wallet already knows about a transaction with the same Txid""? That would clarify why this case is an error a little clearly.  ",https://github.com/bitcoin/bitcoin/pull/23142#discussion_r719683488,719683488,src/wallet/walletdb.cpp
