laanwj,2017-04-21T08:54:45Z,"I thought about this a bit: apparently some people use the stderr output to determine whether a test emitted e.g. sanitizer warnings.\nPossible idea: add a ""WARNINGS"" status, that is interpreted as PASS for the final tally but does show that something unexpected was printed.",https://github.com/bitcoin/bitcoin/pull/10241#issuecomment-296133021,296133021,
jonasschnelli,2017-04-29T14:39:40Z,"Added a new status ""Passed with warnings"" which gets set when the test passed but stderr was not empty. The test will be flagged as ""successful"" for that new status.",https://github.com/bitcoin/bitcoin/pull/10241#issuecomment-298172955,298172955,
MarcoFalke,2017-05-14T10:45:51Z,"Concept ACK, but I will close this pull in case no one picks it up in the next couple of days.",https://github.com/bitcoin/bitcoin/pull/10241#issuecomment-301304185,301304185,
MarcoFalke,2017-05-18T23:49:42Z,Closing for now. Feel free to pick this up again.,https://github.com/bitcoin/bitcoin/pull/10241#issuecomment-302571532,302571532,
MarcoFalke,2017-04-30T10:14:31Z,"```\nNameError: name 'ORANGE' is not defined\n",https://github.com/bitcoin/bitcoin/pull/10241#discussion_r114071832,114071832,test/functional/test_runner.py
jnewbery,2017-05-01T13:29:22Z,`ORANGE` would need to be a constant defined at the top of this file (see around L47),https://github.com/bitcoin/bitcoin/pull/10241#discussion_r114124891,114124891,test/functional/test_runner.py
jnewbery,2017-05-01T13:29:42Z,`elif` please,https://github.com/bitcoin/bitcoin/pull/10241#discussion_r114124914,114124914,test/functional/test_runner.py
