sipa,2016-06-13T13:57:33Z,"This doesn't fix anything. The failure I see is \n\n```\n$ ./fundrawtransaction.py \nInitializing test directory /tmp/test7pcerde1/4231\nMining blocks...\nJSONRPC error: Insufficient funds\n  File ""/home/pw/git/bitcoin/qa/rpc-tests/test_framework/test_framework.py"", line 144, in main\n    self.run_test()\n  File ""./fundrawtransaction.py"", line 684, in run_test\n    result = self.nodes[3].fundrawtr",https://github.com/bitcoin/bitcoin/pull/8200#issuecomment-225588403,225588403,
jonasschnelli,2016-06-13T14:03:29Z,"Updated the PR.\nCould be a timing issues (locked inputs / synced mempools, etc.).\nAdded sync/generate before the new tests.\n\n```\n        self.sync_all()\n        self.nodes[0].generate(1)\n        self.sync_all()\n```\n",https://github.com/bitcoin/bitcoin/pull/8200#issuecomment-225590171,225590171,
sipa,2016-06-13T14:09:59Z,Tested ACK\n,https://github.com/bitcoin/bitcoin/pull/8200#issuecomment-225592035,225592035,
jonasschnelli,2016-06-14T06:55:07Z,Closing in favor or #8201\n,https://github.com/bitcoin/bitcoin/pull/8200#issuecomment-225795114,225795114,
MarcoFalke,2016-06-13T14:10:56Z,Nit: You don't need the sync when you mine on the node where you broadcast the transaction.\n,https://github.com/bitcoin/bitcoin/pull/8200#discussion_r66797702,66797702,qa/rpc-tests/fundrawtransaction.py
MarcoFalke,2016-06-13T14:11:55Z,I think we should get rid of such sync_all() as they pause the test suite quite a bit.\n,https://github.com/bitcoin/bitcoin/pull/8200#discussion_r66797887,66797887,qa/rpc-tests/fundrawtransaction.py
jonasschnelli,2016-06-13T14:32:28Z,I guess there are many places where we do this.\nWhat about fixing all together in an upcoming PR?\n,https://github.com/bitcoin/bitcoin/pull/8200#discussion_r66801854,66801854,qa/rpc-tests/fundrawtransaction.py
MarcoFalke,2016-06-13T15:10:23Z,"Sure, but let's not make it worse if there is no reason to do so.\n",https://github.com/bitcoin/bitcoin/pull/8200#discussion_r66809002,66809002,qa/rpc-tests/fundrawtransaction.py
