fanquake,2016-05-06T09:35:49Z,Will also close #8005\n,https://github.com/bitcoin/bitcoin/pull/8016#issuecomment-217397582,217397582,
MarcoFalke,2016-05-06T09:45:04Z,Tested ACK \n\n28655b8:\n\n```\n$ for i in {1..10000}; do timeout 1 src/test/test_bitcoin --run_test=scheduler_tests &> /dev/null ;echo $? >> /tmp/res ;done;cat /tmp/res|sort|uniq -c\n   9630 0\n    370 124\n```\n\n70af981:\n\n```\n$ rm /tmp/res; for i in {1..10000}; do timeout 1 src/test/test_bitcoin --run_test=scheduler_tests &> /dev/null ;echo $? >> /tmp/res ;done;cat /tmp/res|sort|uniq -c\n  1,https://github.com/bitcoin/bitcoin/pull/8016#issuecomment-217399137,217399137,
laanwj,2016-05-06T13:34:14Z,Thanks for fixing this!\n,https://github.com/bitcoin/bitcoin/pull/8016#issuecomment-217442066,217442066,
laanwj,2016-05-06T16:16:33Z,"For some reason Travis is failing on this due to python zmq problems. I don't understand why, as there is no Python (or zmq) related change here. Will try to clear Travis' caches.\n",https://github.com/bitcoin/bitcoin/pull/8016#issuecomment-217488115,217488115,
paveljanik,2016-05-06T18:42:39Z,"This is because my branch is based on the pre-python3 merge. Master is python3, thus there is no zmq module for python2...\n",https://github.com/bitcoin/bitcoin/pull/8016#issuecomment-217525793,217525793,
paveljanik,2016-05-06T18:45:47Z,"Rebased should solve this, I think. Maybe travis kick can help now.\n",https://github.com/bitcoin/bitcoin/pull/8016#issuecomment-217526543,217526543,
paveljanik,2016-05-06T21:19:19Z,"This helped. Hmm, shouldn't we temporary add python-zmq back to travis to workaround this?\n\nOr should we modify the test script that requires python's zmq module to dot no anything when there is no such module installed (this could also simplify the tests setup for everyone!)? @MarcoFalke what do you think?\n",https://github.com/bitcoin/bitcoin/pull/8016#issuecomment-217561088,217561088,
MarcoFalke,2016-05-07T10:16:03Z,"@paveljanik python-zmq is already present in `.travis.yml`, you can't add it more than once ;)\n\nI changed it (#7851) to fail instead, so errors are detected (and not silently ignored). The travis failure was an error due to broken cache. I think @laanwj cleared the cache and the travis issue is now fixed.\n",https://github.com/bitcoin/bitcoin/pull/8016#issuecomment-217627037,217627037,
MarcoFalke,2016-05-07T10:16:20Z,ut re-ACK 166e4b0\n,https://github.com/bitcoin/bitcoin/pull/8016#issuecomment-217627053,217627053,
paveljanik,2016-05-07T15:54:34Z,"@MarcoFalke there is python3-zmq, not python-zmq...\n",https://github.com/bitcoin/bitcoin/pull/8016#issuecomment-217646610,217646610,
theuni,2016-05-07T17:39:15Z,Does it need to signal in the catch/rethrow case as well?\n,https://github.com/bitcoin/bitcoin/pull/8016#issuecomment-217655300,217655300,
paveljanik,2016-05-08T07:47:56Z,"@theuni I think rethrow case is there only for `f` throwing some exception. It is not a case for our multithread test. But in general, yes, I think there could be the same problem for exception throwing `f`.\n",https://github.com/bitcoin/bitcoin/pull/8016#issuecomment-217701923,217701923,
laanwj,2016-05-10T09:09:25Z,@paveljanik Are you going to fix that here?\n,https://github.com/bitcoin/bitcoin/pull/8016#issuecomment-218101323,218101323,
paveljanik,2016-05-10T09:45:21Z,"No. I'm think about writing another test that will use the exception calls, but not here and not now, sorry.\n",https://github.com/bitcoin/bitcoin/pull/8016#issuecomment-218109455,218109455,
laanwj,2016-05-10T10:08:01Z,"No need to be sorry, thanks for your fix! just needed clarity about which state this pull is in.\n\nutACK 166e4b0\n",https://github.com/bitcoin/bitcoin/pull/8016#issuecomment-218114601,218114601,
